imports_granularity = "Module"
indent_style = "Block"
reorder_imports = true
enum_discrim_align_threshold = 20
max_width = 80
doc_comment_code_block_width = 80
use_small_heuristics = "Max"
# fn_single_line = true
format_code_in_doc_comments = true
format_strings = true
imports_layout = "Vertical"
newline_style = "Unix"
normalize_comments = true
normalize_doc_attributes = true
reorder_impl_items = true
group_imports = "StdExternalCrate"
struct_field_align_threshold = 20
# tab_spaces = 2
use_field_init_shorthand = true
where_single_line = true
wrap_comments = true
